name: home_-_particles
timestamp: 1484008825
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1483801905
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  menu:
    menu-6409: Menu
  social:
    social-3171: Social
  logo:
    logo-9608: 'Logo / Image'
    logo-8966: 'Logo / Image'
  owlcarousel:
    owlcarousel-2455: 'Owl Carousel'
  custom:
    custom-5807: Intro
    custom-1460: Features
  copyright:
    copyright-2517: Copyright
  totop:
    totop-2308: 'To Top'
  mobile-menu:
    mobile-menu-7062: Mobile-menu
inherit:
  default:
    footer: footer
    offcanvas: offcanvas
    logo-8966: logo-9571
    copyright-2517: copyright-1736
    totop-2308: totop-8670
    mobile-menu-7062: mobile-menu-5697
